pip install ctypes
pip install shutil
pip install browser_cookie3
pip install psutil
pip install win32crypt
pip install base64
pip install b64
pip install requests
pip install discord
pip install colorama
pip install re
pip install crypto
pip install sqlite3
pip install marshal
pip install zlib
pip install requests
pip install pystyle
pip install os
pip install shutil
pip install pyinstaller
pip install datetime
pip install dhooks
